//////////////////////////////////////////////////////////////////////
// C++ source file generated by SpecC V2.2.1
// Design: susan_edge_detector
// File:   susan_edge_detector.cc
// Time:   Thu Nov  9 19:50:34 2017
//////////////////////////////////////////////////////////////////////

// Note: User-defined include files are inlined in this file.

// Note: System-defined include files are inlined in this file.

#include "susan_edge_detector.h"


unsigned int _IDcnt = 0;
// channel class definitions /////////////////////////////////////////

HardwareBusTLM::HardwareBusTLM(bit<_BITLEN(15,0),true> (&A), bit<_BITLEN(31,0),true> (&D))
    : _specc::channel(), A(A), D(D)
{   
}

HardwareBusTLM::~HardwareBusTLM(void)
{   
}

#line 59 "./HWBus.sc"
void HardwareBusTLM::masterRead(bit<_BITLEN(15,0),true> a, bit<_BITLEN(31,0),true> *d)
{   
    A = a;
    _specc::notify(event(&ready), ((void*)0));

    _specc::wait(event(&ack), ((void*)0));
     *d = D;
    _specc::waitfor((20000));
}

#line 49 "./HWBus.sc"
void HardwareBusTLM::masterWrite(bit<_BITLEN(15,0),true> a, bit<_BITLEN(31,0),true> d)
{   
    A = a;
    D = d;
    _specc::waitfor((15000));
    _specc::notify(event(&ready), ((void*)0));

    _specc::wait(event(&ack), ((void*)0));
}

#line 82 "./HWBus.sc"
void HardwareBusTLM::slaveRead(bit<_BITLEN(15,0),true> a, bit<_BITLEN(31,0),true> *d)
{   
    _specc::wait(event(&ready), ((void*)0));

    while(a != A) {
	_specc::waitfor((1000));
	_specc::wait(event(&ready), ((void*)0));
    }
     *d = D;
    _specc::waitfor((19000));
    _specc::notify(event(&ack), ((void*)0));
}

#line 69 "./HWBus.sc"
void HardwareBusTLM::slaveWrite(bit<_BITLEN(15,0),true> a, bit<_BITLEN(31,0),true> d)
{   
    _specc::wait(event(&ready), ((void*)0));

    while(a != A) {
	_specc::waitfor((1000));
	_specc::wait(event(&ready), ((void*)0));
    }
    D = d;
    _specc::waitfor((19000));
    _specc::notify(event(&ack), ((void*)0));
}

#line 78 "susan_edge_detector.cc"
MasterHardwareSyncDetect::MasterHardwareSyncDetect(i_receive (&intr))
    : _specc::channel(), intr(intr)
{   
}

MasterHardwareSyncDetect::~MasterHardwareSyncDetect(void)
{   
}

#line 101 "./HWBus.sc"
void MasterHardwareSyncDetect::receive(void)
{   
    intr.receive();
}

#line 94 "susan_edge_detector.cc"
SlaveHardwareSyncGenerate::SlaveHardwareSyncGenerate(i_send (&intr))
    : _specc::channel(), intr(intr)
{   
}

SlaveHardwareSyncGenerate::~SlaveHardwareSyncGenerate(void)
{   
}

#line 121 "./HWBus.sc"
void SlaveHardwareSyncGenerate::send(void)
{   
    intr.send();
}

#line 110 "susan_edge_detector.cc"
MasterHardwareBusLinkAccess::MasterHardwareBusLinkAccess(IMasterHardwareBusTLM (&tlm))
    : _specc::channel(), tlm(tlm)
{   
}

MasterHardwareBusLinkAccess::~MasterHardwareBusLinkAccess(void)
{   
}

#line 177 "./HWBus.sc"
void MasterHardwareBusLinkAccess::MasterRead(int addr, void *data, unsigned long int len)
{   
    unsigned long int i;
    unsigned char *p;
    bit<_BITLEN(31,0),true> word;

    for(p = (unsigned char *)data , i = 0; i < len; i++  , p++ )
    {   
	if ( !(i % 4u)) {
	    tlm.masterRead(addr,  &word);
	}

	 *p = ((unsigned char)((word(31,0, 31,24))).toInt());
	word = word << 8;
    }
}

#line 155 "./HWBus.sc"
void MasterHardwareBusLinkAccess::MasterWrite(int addr, const void *data, unsigned long int len)
{   
    unsigned long int i;
    unsigned char *p;
    bit<_BITLEN(31,0),true> word = bit<32,true>("00000000000000000000000000000000");

    for(p = (unsigned char *)data , i = 0; i < len; i++  , p++ )
    {   
	word = (word << 8) +  *p;

	if ( !((i + 1) % 4u)) {
	    tlm.masterWrite(addr, word);
	    word = 0;
	}
    }

    if (i % 4u) {
	word <<= 8 * (4u - (i % 4u));
	tlm.masterWrite(addr, word);
    }
}

#line 161 "susan_edge_detector.cc"
SlaveHardwareBusLinkAccess::SlaveHardwareBusLinkAccess(ISlaveHardwareBusTLM (&tlm))
    : _specc::channel(), tlm(tlm)
{   
}

SlaveHardwareBusLinkAccess::~SlaveHardwareBusLinkAccess(void)
{   
}

#line 220 "./HWBus.sc"
void SlaveHardwareBusLinkAccess::SlaveRead(int addr, void *data, unsigned long int len)
{   
    unsigned long int i;
    unsigned char *p;
    bit<_BITLEN(31,0),true> word;

    for(p = (unsigned char *)data , i = 0; i < len; i++  , p++ )
    {   
	if ( !(i % 4u)) {
	    tlm.slaveRead(addr,  &word);
	}

	 *p = ((unsigned char)((word(31,0, 31,24))).toInt());
	word = word << 8;
    }
}

#line 198 "./HWBus.sc"
void SlaveHardwareBusLinkAccess::SlaveWrite(int addr, const void *data, unsigned long int len)
{   
    unsigned long int i;
    unsigned char *p;
    bit<_BITLEN(31,0),true> word = bit<32,true>("00000000000000000000000000000000");

    for(p = (unsigned char *)data , i = 0; i < len; i++  , p++ )
    {   
	word = (word << 8) +  *p;

	if ( !((i + 1) % 4u)) {
	    tlm.slaveWrite(addr, word);
	    word = 0;
	}
    }

    if (i % 4u) {
	word <<= 8 * (4u - (i % 4u));
	tlm.slaveWrite(addr, word);
    }
}

#line 212 "susan_edge_detector.cc"
HardwareBus::HardwareBus()
    : _specc::channel(),
    MasterSync0(intr0),
    MasterSync1(intr1),
    SlaveSync0(intr0),
    SlaveSync1(intr1),
    intr0(),
    intr1()
{   
}

HardwareBus::~HardwareBus(void)
{   
}

#line 299 "./HWBus.sc"
void HardwareBus::MasterRead(unsigned short int addr, void *data, unsigned long int len) {
    unsigned long int i;
    unsigned char *tmp;
    A = addr;
    _specc::notify(event(&ready), ((void*)0));

    _specc::wait(event(&ack), ((void*)0));
    tmp = (unsigned char *)data;
    for(i = 0; i < len; i++ ) {
	tmp[i] = D[i];
    }
    _specc::waitfor((20000 * len));
}

#line 369 "./HWBus.sc"
void HardwareBus::MasterSync0Receive() {
    MasterSync0.receive();
}

#line 377 "./HWBus.sc"
void HardwareBus::MasterSync1Receive() {
    MasterSync1.receive();
}

#line 315 "./HWBus.sc"
void HardwareBus::MasterWrite(unsigned short int addr, const void *data, unsigned long int len) {
    unsigned long int i;
    unsigned char *tmp;
    A = addr;
    tmp = (unsigned char *)data;
    for(i = 0; i < len; i++ ) {
	D[i] = tmp[i];
    }
    _specc::waitfor((15000 * len));
    _specc::notify(event(&ready), ((void*)0));

    _specc::wait(event(&ack), ((void*)0));
}



void HardwareBus::SlaveRead(unsigned short int addr, void *data, unsigned long int len) {
    unsigned long int i;
    unsigned char *tmp;
    _specc::wait(event(&ready), ((void*)0));

    while(addr != A) {
	_specc::waitfor((1000));
	_specc::wait(event(&ready), ((void*)0));
    }
    tmp = (unsigned char *)data;
    for(i = 0; i < len; i++ ) {
	tmp[i] = D[i];
    }
    _specc::waitfor((19000 * len));
    _specc::notify(event(&ack), ((void*)0));
}

#line 373 "./HWBus.sc"
void HardwareBus::SlaveSync0Send() {
    SlaveSync0.send();
}

#line 381 "./HWBus.sc"
void HardwareBus::SlaveSync1Send() {
    SlaveSync1.send();
}

#line 350 "./HWBus.sc"
void HardwareBus::SlaveWrite(unsigned short int addr, const void *data, unsigned long int len) {
    unsigned long int i;
    unsigned char *tmp;
    _specc::wait(event(&ready), ((void*)0));

    while(addr != A) {
	_specc::waitfor((1000));
	_specc::wait(event(&ready), ((void*)0));
    }
    tmp = (unsigned char *)data;
    for(i = 0; i < len; i++ ) {
	D[i] = tmp[i];
    }
    _specc::waitfor((19000 * len));
    _specc::notify(event(&ack), ((void*)0));
}

#line 315 "susan_edge_detector.cc"
MasterDriver::MasterDriver(IMasterHardwareBus (&bus), const int (&address))
    : _specc::channel(), bus(bus), address(address)
{   
}

MasterDriver::~MasterDriver(void)
{   
}

#line 401 "./HWBus.sc"
void MasterDriver::receive(void *d, unsigned long int l) {

    if (address == 0) {
	bus.MasterSync0Receive();

	bus.MasterRead(address, d, l);
    }
    else 

#line 407 "./HWBus.sc"
    {   
	bus.MasterSync1Receive();

	bus.MasterRead(address, d, l);
    }
}

#line 388 "./HWBus.sc"
void MasterDriver::send(const void *d, unsigned long int l) {

    if (address == 0) {
	bus.MasterSync0Receive();

	bus.MasterWrite(address, d, l);
    }
    else 

#line 394 "./HWBus.sc"
    {   
	bus.MasterSync1Receive();

	bus.MasterWrite(address, d, l);
    }
}

#line 361 "susan_edge_detector.cc"
SlaveDriver::SlaveDriver(ISlaveHardwareBus (&bus), const int (&address))
    : _specc::channel(), bus(bus), address(address)
{   
}

SlaveDriver::~SlaveDriver(void)
{   
}

#line 431 "./HWBus.sc"
void SlaveDriver::receive(void *d, unsigned long int l) {

    if (address == 0) {
	bus.SlaveSync0Send();

	bus.SlaveRead(address, d, l);
    }
    else 

#line 437 "./HWBus.sc"
    {   
	bus.SlaveSync1Send();

	bus.SlaveRead(address, d, l);
    }
}

#line 418 "./HWBus.sc"
void SlaveDriver::send(const void *d, unsigned long int l) {

    if (address == 0) {
	bus.SlaveSync0Send();

	bus.SlaveWrite(address, d, l);
    }
    else 

#line 424 "./HWBus.sc"
    {   
	bus.SlaveSync1Send();

	bus.SlaveWrite(address, d, l);
    }
}

#line 407 "susan_edge_detector.cc"
OS_channel::OS_channel()
    : _specc::channel()
{   
}

OS_channel::~OS_channel(void)
{   
}

#line 196 "./OS_channel.sc"
void OS_channel::activate(int task_ind)
{   
    Tasks[task_ind].active = 1;
}

#line 137 "./OS_channel.sc"
int OS_channel::create()
{   
    int i;
    int found = 0;

    for(i = 0; i < last_task; i++ )
    {   
	if (Tasks[i].alive == 0)
	{   
	    Tasks[i].alive = 1;
	    Tasks[i].active = 1;
	    found = 1;
	    break;
	}
    }
    if (found == 0) {
	Tasks[last_task].alive = 1;
	Tasks[last_task].active = 1;
	i = last_task;
	last_task++ ;
    }

    return i;
}

#line 166 "./OS_channel.sc"
void OS_channel::dispatch()
{   
    int i;
    for(i = 0; i < last_task; i++ )
    {   
	if (Tasks[(cur_task + i + 1) % last_task].alive == 1)
	{   
	    if (Tasks[(cur_task + i + 1) % last_task].active == 1)
	    {   
		cur_task = (cur_task + i + 1) % last_task;
		notifyTask(cur_task);

		break;
	    }
	}
    }
    print();
}

#line 162 "./OS_channel.sc"
int OS_channel::getMyID() {
    return cur_task;
}

#line 117 "./OS_channel.sc"
void OS_channel::init()
{   
    int i;
    for(i = 0; i < 100; i++ )
    {   
	Tasks[i].alive = 0;
	Tasks[i].active = 0;
    }
    last_task = 0;
    cur_task =  -1;
}

#line 185 "./OS_channel.sc"
void OS_channel::kill()
{   
    int my_task_ind;

    my_task_ind = cur_task;
    dispatch();
    Tasks[my_task_ind].alive = 0;
    Tasks[my_task_ind].active = 0;
}

#line 48 "./OS_channel.sc"
void OS_channel::notifyTask(int task_ind)
{   
    switch(task_ind)
    {   
	case 0: _specc::notify(event(&E0), ((void*)0));
	break;
	case 1: _specc::notify(event(&E1), ((void*)0));
	break;
	case 2: _specc::notify(event(&E2), ((void*)0));
	break;
	case 3: _specc::notify(event(&E3), ((void*)0));
	break;
	case 4: _specc::notify(event(&E4), ((void*)0));
	break;
	case 5: _specc::notify(event(&E5), ((void*)0));
	break;
	case 6: _specc::notify(event(&E6), ((void*)0));
	break;
	case 7: _specc::notify(event(&E7), ((void*)0));
	break;
	case 8: _specc::notify(event(&E8), ((void*)0));
	break;
	case 9: _specc::notify(event(&E9), ((void*)0));
	break;
	default:
	    while(1) ;

	break;
    }
}

#line 216 "./OS_channel.sc"
void OS_channel::par_end(int task_ind) {
    Tasks[task_ind].active = 1;
    if (cur_task != task_ind) dispatch();
    waitTask(task_ind);
}

#line 211 "./OS_channel.sc"
void OS_channel::par_start(int task_ind) {
    Tasks[task_ind].active = 0;
    dispatch();
}

#line 235 "./OS_channel.sc"
void OS_channel::post_wait(int task_ind) {
    Tasks[task_ind].active = 1;
    if (cur_task != task_ind) dispatch();
    waitTask(task_ind);
}

#line 227 "./OS_channel.sc"
int OS_channel::pre_wait(void) {
    int my_id;
    my_id = cur_task;
    Tasks[my_id].active = 0;
    dispatch();
    return my_id;
}

#line 110 "./OS_channel.sc"
void OS_channel::print(void) {
    int i;
    for(i = 0; i < last_task; i++ ) {
    }
}

#line 130 "./OS_channel.sc"
int OS_channel::start(int task_ind)
{   
    cur_task = task_ind;
    notifyTask(cur_task);
    return last_task;
}

#line 222 "./OS_channel.sc"
void OS_channel::timewait(int time) {
    _specc::waitfor((time));
    yield();
}

#line 79 "./OS_channel.sc"
void OS_channel::waitTask(int task_ind)
{   
    switch(task_ind)
    {   
	case 0: _specc::wait(event(&E0), ((void*)0));
	break;
	case 1: _specc::wait(event(&E1), ((void*)0));
	break;
	case 2: _specc::wait(event(&E2), ((void*)0));
	break;
	case 3: _specc::wait(event(&E3), ((void*)0));
	break;
	case 4: _specc::wait(event(&E4), ((void*)0));
	break;
	case 5: _specc::wait(event(&E5), ((void*)0));
	break;
	case 6: _specc::wait(event(&E6), ((void*)0));
	break;
	case 7: _specc::wait(event(&E7), ((void*)0));
	break;
	case 8: _specc::wait(event(&E8), ((void*)0));
	break;
	case 9: _specc::wait(event(&E9), ((void*)0));
	break;
	default:

	    while(1) ;
	break;
    }
}

#line 201 "./OS_channel.sc"
void OS_channel::yield()
{   
    int my_task_ind;

    my_task_ind = cur_task;

    dispatch();
    waitTask(my_task_ind);
}

#line 623 "susan_edge_detector.cc"
c_double_handshake_signal::c_double_handshake_signal()
    : _specc::channel(),
    v(false),
    w(false)
{   
}

c_double_handshake_signal::~c_double_handshake_signal(void)
{   
}

#line 14 "./c_double_handshake_signal.sc"
void c_double_handshake_signal::receive(void)
{   
    if ( !v)
    {   
	w = true;
	_specc::wait(event(&req), ((void*)0));
	w = false;
    }
    v = false;
    _specc::notify(event(&ack), ((void*)0));
    _specc::wait(event(&ack), ((void*)0));
}

void c_double_handshake_signal::send(void)
{   
    v = true;
    if (w)
    {   
	_specc::notify(event(&req), ((void*)0));
    }
    _specc::wait(event(&ack), ((void*)0));
}

#line 659 "susan_edge_detector.cc"
c_int7220_queue_os::c_int7220_queue_os(const unsigned long int (&size), OSAPI (&os))
    : _specc::channel(), size(size), os(os),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   
}

c_int7220_queue_os::~c_int7220_queue_os(void)
{   
}

#line 8 "./c_int7220_queue_os.sc"
void c_int7220_queue_os::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 8 "./c_int7220_queue_os.sc"
void c_int7220_queue_os::receive(int (*d)[7220]) { int my_id; while( !n) { wr++ ; my_id = os.pre_wait(); _specc::wait(event(&r), ((void*)0)); os.post_wait(my_id); wr-- ;
    }

#line 8 "./c_int7220_queue_os.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 8 "./c_int7220_queue_os.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 8 "./c_int7220_queue_os.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 8 "./c_int7220_queue_os.sc"
    cleanup();
}

#line 8 "./c_int7220_queue_os.sc"
void c_int7220_queue_os::send(int d[7220]) { int my_id; while(n >= size) { ws++ ; my_id = os.pre_wait(); _specc::wait(event(&s), ((void*)0)); os.post_wait(my_id); ws-- ;
    }

#line 8 "./c_int7220_queue_os.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 8 "./c_int7220_queue_os.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 8 "./c_int7220_queue_os.sc"
void c_int7220_queue_os::setup(void) { if ( !buffer) { int dummy[7220]; unsigned long int i; if ( !(buffer = (int (*)[7220])malloc(sizeof(int [7220]) * size))) { perror("c_typed_queue_os"); abort();
	}

#line 8 "./c_int7220_queue_os.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(int [7220]));
	}
    }
}

#line 723 "susan_edge_detector.cc"
c_uchar7220_queue_os::c_uchar7220_queue_os(const unsigned long int (&size), OSAPI (&os))
    : _specc::channel(), size(size), os(os),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   
}

c_uchar7220_queue_os::~c_uchar7220_queue_os(void)
{   
}

#line 8 "./c_uchar7220_queue_os.sc"
void c_uchar7220_queue_os::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 8 "./c_uchar7220_queue_os.sc"
void c_uchar7220_queue_os::receive(unsigned char (*d)[7220]) { int my_id; while( !n) { wr++ ; my_id = os.pre_wait(); _specc::wait(event(&r), ((void*)0)); os.post_wait(my_id); wr-- ;
    }

#line 8 "./c_uchar7220_queue_os.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 8 "./c_uchar7220_queue_os.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 8 "./c_uchar7220_queue_os.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 8 "./c_uchar7220_queue_os.sc"
    cleanup();
}

#line 8 "./c_uchar7220_queue_os.sc"
void c_uchar7220_queue_os::send(unsigned char d[7220]) { int my_id; while(n >= size) { ws++ ; my_id = os.pre_wait(); _specc::wait(event(&s), ((void*)0)); os.post_wait(my_id); ws-- ;
    }

#line 8 "./c_uchar7220_queue_os.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 8 "./c_uchar7220_queue_os.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 8 "./c_uchar7220_queue_os.sc"
void c_uchar7220_queue_os::setup(void) { if ( !buffer) { unsigned char dummy[7220]; unsigned long int i; if ( !(buffer = (unsigned char (*)[7220])malloc(sizeof(unsigned char [7220]) * size))) { perror("c_typed_queue_os"); abort();
	}

#line 8 "./c_uchar7220_queue_os.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(unsigned char [7220]));
	}
    }
}

#line 787 "susan_edge_detector.cc"
c_double_handshake::c_double_handshake()
    : _specc::channel(),
    v(false),
    w(false)
{   
}

c_double_handshake::~c_double_handshake(void)
{   
}

#line 84 "c_double_handshake.sc"
void c_double_handshake::receive(void *d, unsigned long int l)
{   
    if ( !v)
    {   
	w = true;
	_specc::wait(event(&req), ((void*)0));
	w = false;
    }
    if (l != tmpl)
    {   
	abort();
    }
    memcpy(d, tmpd, l);
    v = false;
    _specc::notify(event(&ack), ((void*)0));
    _specc::wait(event(&ack), ((void*)0));
}

void c_double_handshake::send(const void *d, unsigned long int l)
{   
    tmpd = d;
    tmpl = l;
    v = true;
    if (w)
    {   
	_specc::notify(event(&req), ((void*)0));
    }
    _specc::wait(event(&ack), ((void*)0));
}

#line 830 "susan_edge_detector.cc"
c_handshake::c_handshake()
    : _specc::channel(),
    f(false),
    w(false)
{   
}

c_handshake::~c_handshake(void)
{   
}

#line 62 "c_handshake.sc"
void c_handshake::receive(void)
{   
    if ( !f)
    {   
	w = true;
	_specc::wait(event(&e), ((void*)0));
	w = false;
    }
    f = false;
}

void c_handshake::send(void)
{   
    if (w)
    {   
	_specc::notify(event(&e), ((void*)0));
    }
    f = true;
}

#line 863 "susan_edge_detector.cc"
c_queue::c_queue(const unsigned long int (&size))
    : _specc::channel(), size(size),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   
}

c_queue::~c_queue(void)
{   
}

#line 102 "c_queue.sc"
void c_queue::cleanup(void)
{   
    if ( !n)
    {   
	free(buffer);
	buffer = 0;
    }
}

void c_queue::receive(void *d, unsigned long int l)
{   
    unsigned long int p0;

    while(l > n)
    {   
	wr++ ;
	_specc::wait(event(&r), ((void*)0));
	wr-- ;
    }

    if (n <= p)
    {   
	p0 = p - n;
    }
    else 
    {   
	p0 = p + size - n;
    }
    if (l <= size - p0)
    {   
	memcpy(d,  &buffer[p0], l);
	n -= l;
    }
    else 
    {   
	memcpy(d,  &buffer[p0], size - p0);
	memcpy(((char *)d) + (size - p0),  &buffer[0], l - (size - p0));
	n -= l;
    }

    if (ws)
    {   
	_specc::notify(event(&s), ((void*)0));
    }

    cleanup();
}

void c_queue::send(const void *d, unsigned long int l)
{   
    while(l > size - n)
    {   
	ws++ ;
	_specc::wait(event(&s), ((void*)0));
	ws-- ;
    }

    setup();

    if (l <= size - p)
    {   
	memcpy( &buffer[p], d, l);
	p += l;
	n += l;
    }
    else 
    {   
	memcpy( &buffer[p], d, size - p);
	memcpy( &buffer[0], ((char *)d) + (size - p), l - (size - p));
	p = l - (size - p);
	n += l;
    }

    if (wr)
    {   
	_specc::notify(event(&r), ((void*)0));
    }
}

#line 90 "c_queue.sc"
void c_queue::setup(void)
{   
    if ( !buffer)
    {   
	if ( !(buffer = (char *)malloc(size)))
	{   
	    perror("c_queue");
	    abort();
	}
    }
}

#line 971 "susan_edge_detector.cc"
c_uchar7220_queue::c_uchar7220_queue(const unsigned long int (&size))
    : _specc::channel(), size(size),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   
}

c_uchar7220_queue::~c_uchar7220_queue(void)
{   
}

#line 8 "c_uchar7220_queue.sc"
void c_uchar7220_queue::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 8 "c_uchar7220_queue.sc"
void c_uchar7220_queue::receive(unsigned char (*d)[7220]) { while( !n) { wr++ ; _specc::wait(event(&r), ((void*)0)); wr-- ;
    }

#line 8 "c_uchar7220_queue.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 8 "c_uchar7220_queue.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 8 "c_uchar7220_queue.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 8 "c_uchar7220_queue.sc"
    cleanup();
}

#line 8 "c_uchar7220_queue.sc"
void c_uchar7220_queue::send(unsigned char d[7220]) { while(n >= size) { ws++ ; _specc::wait(event(&s), ((void*)0)); ws-- ;
    }

#line 8 "c_uchar7220_queue.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 8 "c_uchar7220_queue.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 8 "c_uchar7220_queue.sc"
void c_uchar7220_queue::setup(void) { if ( !buffer) { unsigned char dummy[7220]; unsigned long int i; if ( !(buffer = (unsigned char (*)[7220])malloc(sizeof(unsigned char [7220]) * size))) { perror("c_typed_queue"); abort();
	}

#line 8 "c_uchar7220_queue.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(unsigned char [7220]));
	}
    }
}

// behavior class definitions ////////////////////////////////////////

#line 1037 "susan_edge_detector.cc"
PE1::PE1(unsigned int _idcnt, i_receiver (&in_image), i_sender (&out_image))
    : _specc::behavior(_idcnt), in_image(in_image), out_image(out_image),
    TASK_PE1(_IDcnt, in_image, out_image, os),
    os()
{   
}

PE1::~PE1(void)
{   
}

#line 17 "design.sc"
void PE1::main(void) {
    os.init();
    task_id = TASK_PE1.init();
    os.start(task_id);

    TASK_PE1.main();
}

#line 1058 "susan_edge_detector.cc"
INPUT::INPUT(unsigned int _idcnt, i_receive (&start), unsigned char (&image_buffer)[7220], i_sender (&in_image))
    : _specc::behavior(_idcnt), start(start), image_buffer(image_buffer), in_image(in_image),
    read_image(_IDcnt, start, image_buffer, in_image)
{   
}

INPUT::~INPUT(void)
{   
}

#line 30 "design.sc"
void INPUT::main(void) {
    read_image.main();
}

#line 1074 "susan_edge_detector.cc"
OUTPUT::OUTPUT(unsigned int _idcnt, i_receiver (&out_image), i_sender (&out_image_susan))
    : _specc::behavior(_idcnt), out_image(out_image), out_image_susan(out_image_susan),
    write_image(_IDcnt, out_image, out_image_susan)
{   
}

OUTPUT::~OUTPUT(void)
{   
}

#line 39 "design.sc"
void OUTPUT::main(void) {
    write_image.main();
}

#line 1090 "susan_edge_detector.cc"
Design::Design(unsigned int _idcnt, i_receive (&start), unsigned char (&image_buffer)[7220], i_sender (&out_image_susan))
    : _specc::behavior(_idcnt), start(start), image_buffer(image_buffer), out_image_susan(out_image_susan),
    INPUT_ADDR(0),
    OUTPUT_ADDR(1),
    bus(),
    in_image_master(bus, INPUT_ADDR),
    in_image_slave(bus, INPUT_ADDR),
    input(++_IDcnt, start, image_buffer, in_image_slave),
    out_image_master(bus, OUTPUT_ADDR),
    out_image_slave(bus, OUTPUT_ADDR),
    output(++_IDcnt, out_image_slave, out_image_susan),
    pe1(++_IDcnt, in_image_master, out_image_master)
{   
}

Design::~Design(void)
{   
}

#line 69 "design.sc"
void Design::main(void) {
    { _specc::fork _scc_fork_0(&input), _scc_fork_1(&pe1), _scc_fork_2(&output); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, 
	    &_scc_fork_2, ((_specc::fork*)0));
    }
}

#line 1119 "susan_edge_detector.cc"
DetectEdges::DetectEdges(unsigned int _idcnt, i_receiver (&in_image), i_int7220_sender_os (&out_r), i_uchar7220_sender_os (&out_mid), i_uchar7220_sender_os (&out_image), OSAPI (&os))
    : _specc::behavior(_idcnt), in_image(in_image), out_r(out_r), out_mid(out_mid), out_image(out_image), os(os),
    setup_brightness_lut(_IDcnt, bp, os),
    susan_edges(_IDcnt, in_image, out_r, out_mid, bp, out_image, os)
{   
}

DetectEdges::~DetectEdges(void)
{   
}

#line 19 "detect_edges.sc"
void DetectEdges::main(void) {

    setup_brightness_lut.main();

    susan_edges.main();


    os.print();
}

#line 1142 "susan_edge_detector.cc"
Edges::Edges(unsigned int _idcnt, i_receiver (&in_image), i_int7220_sender_os (&out_r), i_uchar7220_sender_os (&out_mid), i_uchar7220_sender_os (&out_image), OSAPI (&os))
    : _specc::behavior(_idcnt), in_image(in_image), out_r(out_r), out_mid(out_mid), out_image(out_image), os(os),
    detect_edges(_IDcnt, in_image, out_r, out_mid, out_image, os)
{   
}

Edges::~Edges(void)
{   
}

#line 36 "detect_edges.sc"
int Edges::init(void) {
    my_id = os.create();
    return my_id;
}

void Edges::main(void) {


    os.waitTask(my_id);

    { enum { _scc_state_0, _scc_state_detect_edges } _scc_next_state = _scc_state_detect_edges; do switch(_scc_next_state) {
	    case _scc_state_detect_edges: { detect_edges.main(); { _scc_next_state = _scc_state_detect_edges; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }
    os.kill();
}

#line 1170 "susan_edge_detector.cc"
EdgeDrawThread_PartA::EdgeDrawThread_PartA(unsigned int _idcnt, unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220], int (&thID), OSAPI (&os))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), mid(mid), thID(thID), os(os)
{   
}

EdgeDrawThread_PartA::~EdgeDrawThread_PartA(void)
{   
}

#line 13 "edge_draw.sc"
int EdgeDrawThread_PartA::init(void) {
    my_id = os.create();
    return my_id;
}

void EdgeDrawThread_PartA::main(void) {

    int i;
    unsigned char *inp; unsigned char *midp;
    int drawing_mode;

    os.waitTask(my_id);
    drawing_mode = 0;
    if (drawing_mode == 0)
    {   

	midp = mid + 7220 / 2 * thID;
	for(i = 76 * 95 / 2 * thID; i < 76 * 95 / 2 * (thID + 1) + (thID + 1 == 2 && 76 * 95 % 2 != 0 ? 76 * 95 % 2 : 0); i++ )
	{   
	    if ( *midp < 8)
	    {   
		inp = image_buffer + (midp - mid) - 76 - 1;
		 *inp++  = 255;  *inp++  = 255;  *inp = 255; inp += 76 - 2;
		 *inp++  = 255;  *inp++ ;  *inp = 255; inp += 76 - 2;
		 *inp++  = 255;  *inp++  = 255;  *inp = 255;
	    }
	    midp++ ;
	}
    }
    os.kill();
}

#line 1213 "susan_edge_detector.cc"
EdgeDrawThread_PartB::EdgeDrawThread_PartB(unsigned int _idcnt, unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220], int (&thID), OSAPI (&os))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), mid(mid), thID(thID), os(os)
{   
}

EdgeDrawThread_PartB::~EdgeDrawThread_PartB(void)
{   
}

#line 52 "edge_draw.sc"
int EdgeDrawThread_PartB::init(void) {
    my_id = os.create();
    return my_id;
}

void EdgeDrawThread_PartB::main(void) {

    int i;
    unsigned char *midp;
    int drawing_mode;

    os.waitTask(my_id);
    drawing_mode = 0;


    midp = mid + 7220 / 2 * thID;

    for(i = 76 * 95 / 2 * thID; i < 76 * 95 / 2 * (thID + 1) + (thID + 1 == 2 && 76 * 95 % 2 != 0 ? 76 * 95 % 2 : 0); i++ )
    {   
	if ( *midp < 8)
	     *(image_buffer + (midp - mid)) = 0;
	midp++ ;
    }
    os.kill();
}

#line 1250 "susan_edge_detector.cc"
EdgeDraw_ReadInput::EdgeDraw_ReadInput(unsigned int _idcnt, i_uchar7220_receiver_os (&in_image), i_uchar7220_receiver_os (&in_mid), unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220])
    : _specc::behavior(_idcnt), in_image(in_image), in_mid(in_mid), image_buffer(image_buffer), mid(mid)
{   
}

EdgeDraw_ReadInput::~EdgeDraw_ReadInput(void)
{   
}

#line 82 "edge_draw.sc"
void EdgeDraw_ReadInput::main(void) {

    in_image.receive( &image_buffer);

    in_mid.receive( &mid);
}

#line 1268 "susan_edge_detector.cc"
EdgeDraw_WriteOutput::EdgeDraw_WriteOutput(unsigned int _idcnt, unsigned char (&image_buffer)[7220], i_sender (&out_image))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), out_image(out_image)
{   
}

EdgeDraw_WriteOutput::~EdgeDraw_WriteOutput(void)
{   
}

#line 93 "edge_draw.sc"
void EdgeDraw_WriteOutput::main(void) {



    out_image.send(image_buffer, sizeof (image_buffer));
}

#line 1286 "susan_edge_detector.cc"
EdgeDraw_PartA::EdgeDraw_PartA(unsigned int _idcnt, unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220], OSAPI (&os))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), mid(mid), os(os),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    edge_draw_a_thread_0(_IDcnt, image_buffer, mid, _scc_const_port_0, os),
    edge_draw_a_thread_1(_IDcnt, image_buffer, mid, _scc_const_port_1, os)
{   
}

EdgeDraw_PartA::~EdgeDraw_PartA(void)
{   
}

#line 108 "edge_draw.sc"
void EdgeDraw_PartA::main(void) {
    my_id = os.getMyID();
    my_id0 = edge_draw_a_thread_0.init();
    my_id1 = edge_draw_a_thread_1.init();

    os.par_start(my_id);
    { _specc::fork _scc_fork_0(&edge_draw_a_thread_0), _scc_fork_1(&edge_draw_a_thread_1); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, ((_specc::fork*)0));
    }
    os.par_end(my_id);
    os.timewait(12000000);
}

#line 1315 "susan_edge_detector.cc"
EdgeDraw_PartB::EdgeDraw_PartB(unsigned int _idcnt, unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220], OSAPI (&os))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), mid(mid), os(os),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    edge_draw_b_thread_0(_IDcnt, image_buffer, mid, _scc_const_port_0, os),
    edge_draw_b_thread_1(_IDcnt, image_buffer, mid, _scc_const_port_1, os)
{   
}

EdgeDraw_PartB::~EdgeDraw_PartB(void)
{   
}

#line 130 "edge_draw.sc"
void EdgeDraw_PartB::main(void) {
    my_id = os.getMyID();
    my_id0 = edge_draw_b_thread_0.init();
    my_id1 = edge_draw_b_thread_1.init();

    os.par_start(my_id);
    { _specc::fork _scc_fork_0(&edge_draw_b_thread_0), _scc_fork_1(&edge_draw_b_thread_1); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, ((_specc::fork*)0));
    }
    os.par_end(my_id);
    os.timewait(12000000);
}

#line 1344 "susan_edge_detector.cc"
EdgeDraw::EdgeDraw(unsigned int _idcnt, i_uchar7220_receiver_os (&in_image), i_uchar7220_receiver_os (&in_mid), i_sender (&out_image), OSAPI (&os))
    : _specc::behavior(_idcnt), in_image(in_image), in_mid(in_mid), out_image(out_image), os(os),
    edge_draw_a(_IDcnt, image_buffer, mid, os),
    edge_draw_b(_IDcnt, image_buffer, mid, os),
    edge_draw_read_input(_IDcnt, in_image, in_mid, image_buffer, mid),
    edge_draw_write_output(_IDcnt, image_buffer, out_image)
{   
}

EdgeDraw::~EdgeDraw(void)
{   
}

#line 159 "edge_draw.sc"
void EdgeDraw::main(void) {

    { enum { _scc_state_0, _scc_state_edge_draw_read_input, _scc_state_edge_draw_a, _scc_state_edge_draw_b, _scc_state_edge_draw_write_output } _scc_next_state = _scc_state_edge_draw_read_input; do switch(_scc_next_state) {
	    case _scc_state_edge_draw_read_input: { edge_draw_read_input.main(); { _scc_next_state = _scc_state_edge_draw_a; break; } }
	    case _scc_state_edge_draw_a: { edge_draw_a.main(); { _scc_next_state = _scc_state_edge_draw_b; break; } }
	    case _scc_state_edge_draw_b: { edge_draw_b.main(); { _scc_next_state = _scc_state_edge_draw_write_output; break; } }
	    case _scc_state_edge_draw_write_output: { edge_draw_write_output.main(); { _scc_next_state = _scc_state_0; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }
}

#line 1369 "susan_edge_detector.cc"
Draw::Draw(unsigned int _idcnt, i_uchar7220_receiver_os (&in_image), i_uchar7220_receiver_os (&in_mid), i_sender (&out_image), OSAPI (&os))
    : _specc::behavior(_idcnt), in_image(in_image), in_mid(in_mid), out_image(out_image), os(os),
    edge_draw(_IDcnt, in_image, in_mid, out_image, os)
{   
}

Draw::~Draw(void)
{   
}

#line 178 "edge_draw.sc"
int Draw::init(void) {
    my_id = os.create();
    return my_id;
}

void Draw::main(void) {

    os.waitTask(my_id);

    { enum { _scc_state_0, _scc_state_edge_draw } _scc_next_state = _scc_state_edge_draw; do switch(_scc_next_state) {
	    case _scc_state_edge_draw: { edge_draw.main(); { _scc_next_state = _scc_state_edge_draw; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }
    os.kill();
}

#line 1396 "susan_edge_detector.cc"
Monitor::Monitor(unsigned int _idcnt, i_receiver (&img), i_receiver (&start_time_channel))
    : _specc::behavior(_idcnt), img(img), start_time_channel(start_time_channel)
{   
}

Monitor::~Monitor(void)
{   
}

#line 10 "monitor.sc"
void Monitor::main(void)
{   
    struct _IO_FILE *fd;
    unsigned char image_buffer[7220];
    char filename[100];
    int n;
    unsigned long long int start_time;
    for(n = 0; n < 5; n++ )
    {   
	start_time_channel.receive( &start_time, sizeof(unsigned long long int));
	sprintf(filename, "out.pgm");




	if ((fd = fopen(filename, "w")) == ((void *)0))

	{    fprintf(stderr, "Can't output image%s.\n", filename); exit(0);
	}

#line 27 "monitor.sc"
	;

	fprintf(fd, "P5\n");
	fprintf(fd, "%d %d\n", 76, 95);
	fprintf(fd, "255\n");

	img.receive(image_buffer, 7220 * sizeof(char));

	if (fwrite(image_buffer, 76 * 95, 1, fd) != 1)
	{    fprintf(stderr, "Can't write image %s.\n", filename); exit(0);
	}

#line 36 "monitor.sc"
	;

	fclose(fd);
	printf("Total process time: %llu us\n", (now() - start_time) / (1 * 1000000ull));
    }

    printf("Current time: %llu us\n", (now()) / (1 * 1000000ull));
    exit(0);
}

#line 1451 "susan_edge_detector.cc"
ReadImage::ReadImage(unsigned int _idcnt, i_receive (&start), unsigned char (&image_buffer)[7220], i_sender (&out_image))
    : _specc::behavior(_idcnt), start(start), image_buffer(image_buffer), out_image(out_image)
{   
}

ReadImage::~ReadImage(void)
{   
}

#line 10 "read_image.sc"
void ReadImage::main(void) {
    int i;
    unsigned char image_buffer_out[7220];

    while(true) {
	start.receive();
	for(i = 0; i < 7220; i++ )
	    image_buffer_out[i] = image_buffer[i];

	out_image.send(image_buffer_out, sizeof (image_buffer_out));
    }
}

#line 1475 "susan_edge_detector.cc"
SetupBrightnessLutThread::SetupBrightnessLutThread(unsigned int _idcnt, unsigned char (&bp)[516], int (&thID), OSAPI (&os))
    : _specc::behavior(_idcnt), bp(bp), thID(thID), os(os)
{   
}

SetupBrightnessLutThread::~SetupBrightnessLutThread(void)
{   
}

#line 12 "setup_brightness_lut.sc"
int SetupBrightnessLutThread::init(void) {
    my_id = os.create();
    return my_id;
}

void SetupBrightnessLutThread::main(void) {
    int k;
    float temp;
    int form; int thresh;

    thresh = 20;
    form = 6;

    os.waitTask(my_id);


    for(k = ( -256) + 512 / 2 * thID; k < ( -256) + 512 / 2 * thID + 512 / 2 + 1; k++ ) {
	temp = ((float)k) / ((float)thresh);
	temp = temp * temp;
	if (form == 6)
	    temp = temp * temp * temp;
	temp = 1.000000000000000e+02 * exp( -temp);
	bp[(k + 258)] = (unsigned char)temp;
    }
    os.kill();
}

#line 1513 "susan_edge_detector.cc"
SetupBrightnessLut::SetupBrightnessLut(unsigned int _idcnt, unsigned char (&bp)[516], OSAPI (&os))
    : _specc::behavior(_idcnt), bp(bp), os(os),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    setup_brightness_thread_0(_IDcnt, bp, _scc_const_port_0, os),
    setup_brightness_thread_1(_IDcnt, bp, _scc_const_port_1, os)
{   
}

SetupBrightnessLut::~SetupBrightnessLut(void)
{   
}

#line 50 "setup_brightness_lut.sc"
void SetupBrightnessLut::main(void) {
    my_id = os.getMyID();
    my_id0 = setup_brightness_thread_0.init();
    my_id1 = setup_brightness_thread_1.init();

    os.par_start(my_id);

    { _specc::fork _scc_fork_0(&setup_brightness_thread_0), _scc_fork_1(&setup_brightness_thread_1); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, ((_specc::fork*)0));
    }
    os.par_end(my_id);

    os.timewait(2700);
}

#line 1544 "susan_edge_detector.cc"
Stimulus::Stimulus(unsigned int _idcnt, i_send (&start), unsigned char (&image_buffer)[7220], i_sender (&start_time_channel))
    : _specc::behavior(_idcnt), start(start), image_buffer(image_buffer), start_time_channel(start_time_channel)
{   
}

Stimulus::~Stimulus(void)
{   
}

#line 42 "stimulus.sc"
void Stimulus::get_image(char filename[200], unsigned char *image)
{   

    struct _IO_FILE *fd;
    char header[100];
    int tmp; int x_size; int y_size;

#line 53 "stimulus.sc"
    if ((fd = fopen(filename, "r")) == ((void *)0))

    {    fprintf(stderr, "Can't input image %s.\n", filename); exit(0);
    }

#line 55 "stimulus.sc"
    ;


    header[0] = fgetc(fd);
    header[1] = fgetc(fd);
    if ( !(header[0] == 'P' && header[1] == '5'))
    {    fprintf(stderr, "Image %s does not have binary PGM header.\n", filename); exit(0);
    }

#line 61 "stimulus.sc"
    ;

    x_size = getint(fd);
    y_size = getint(fd);
    tmp = getint(fd);

    if ((x_size != 76) || (y_size != 95)) {
	fprintf(stderr, "Input picture does not match size of %dx%d\n", 76, 95);
	fclose(fd);
	exit(1);
    }

    if (fread(image, 1, 76 * 95, fd) == 0)
    {    fprintf(stderr, "Image %s is wrong size.\n", filename); exit(0);
    }

#line 74 "stimulus.sc"
    ;
    fclose(fd);
}

#line 12 "stimulus.sc"
int Stimulus::getint(struct _IO_FILE *fd)
{   
    int c; int i;
    char dummy[10000];

    c = _IO_getc(fd);
    while(1)
    {   
	if (c == '#')
	    fgets(dummy, 9000, fd);
	if (c == ( -1))
	{    fprintf(stderr, "Image %s not binary PGM.\n", "is"); exit(0);
	}

#line 23 "stimulus.sc"
	;
	if (c >= '0' && c <= '9')
	    break;
	c = _IO_getc(fd);
    }


    i = 0;
    while(1) {
	i = (i * 10) + (c - '0');
	c = _IO_getc(fd);
	if (c == ( -1)) return (i);
	if (c < '0' || c > '9') break;
    }

    return (i);
}

#line 79 "stimulus.sc"
void Stimulus::main(void)
{   
    unsigned int n;
    char filename[100];
    unsigned long long int start_time;

    sprintf(filename, "%s", "input_small.pgm");
    get_image(filename, image_buffer);
    for(n = 0; n < 5 + 1; n++ ) {
	printf("Starting process %d...\n", n + 1);
	start.send();
	start_time = now();
	start_time_channel.send( &start_time, sizeof(unsigned long long int));
	_specc::waitfor((1000));
    }
}

#line 1652 "susan_edge_detector.cc"
Susan::Susan(unsigned int _idcnt, i_receiver (&in_image), i_sender (&out_image), OSAPI (&os))
    : _specc::behavior(_idcnt), in_image(in_image), out_image(out_image), os(os),
    _scc_const_port_0(1ul),
    _scc_const_port_1(1ul),
    _scc_const_port_2(1ul),
    _scc_const_port_3(1ul),
    draw(_IDcnt, image_edge_draw, mid_edge_draw, out_image, os),
    edges(_IDcnt, in_image, r, mid, image_edge_draw, os),
    image_edge_draw(_scc_const_port_0, os),
    mid(_scc_const_port_1, os),
    mid_edge_draw(_scc_const_port_2, os),
    r(_scc_const_port_3, os),
    thin(_IDcnt, r, mid, mid_edge_draw, os)
{   
}

Susan::~Susan(void)
{   
}

#line 29 "susan.sc"
int Susan::init(void)
{   
    my_id = os.create();
    return my_id;
}

void Susan::main(void)
{   
    os.waitTask(my_id);

    ed_id = edges.init();
    th_id = thin.init();
    dr_id = draw.init();

    os.par_start(my_id);
    { _specc::fork _scc_fork_0(&edges), _scc_fork_1(&thin), _scc_fork_2(&draw); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, 
	    &_scc_fork_2, ((_specc::fork*)0));
    }
    os.par_end(my_id);

    os.kill();
}

#line 1699 "susan_edge_detector.cc"
Main::Main(unsigned int _idcnt)
    : _specc::class_type(_idcnt),
    _scc_const_port_0(1000ul),
    design(_IDcnt, start, image_buffer, out_image),
    monitor(_IDcnt, out_image, start_time),
    out_image(),
    start(),
    start_time(_scc_const_port_0),
    stimulus(_IDcnt, start, image_buffer, start_time)
{   
}

Main::~Main(void)
{   
}

#line 24 "susan_edge_detector.sc"
int Main::main(void) {
    { _specc::fork _scc_fork_0(&stimulus), _scc_fork_1(&design), _scc_fork_2(&monitor); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, 
	    &_scc_fork_2, ((_specc::fork*)0));
    }

    return 0;
}

#line 1727 "susan_edge_detector.cc"
Main _scc_main(_IDcnt);

int main(void)
{   
    int _scc_main_return;
    
    _specc::start();
    _scc_main_return = _scc_main.main();
    _specc::end();
    return(_scc_main_return);
}

SusanEdgesThread_PartA::SusanEdgesThread_PartA(unsigned int _idcnt, unsigned char (&image_buffer)[7220], int (&r)[7220], unsigned char (&bp)[516], int (&thID), OSAPI (&os))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), r(r), bp(bp), thID(thID), os(os)
{   
}

SusanEdgesThread_PartA::~SusanEdgesThread_PartA(void)
{   
}

#line 13 "susan_edges.sc"
int SusanEdgesThread_PartA::init(void) {
    my_id = os.create();
    return my_id;
}

void SusanEdgesThread_PartA::main(void) {

    int max_no;
    int i; int j; int n;
    unsigned char *cp; unsigned char *p;

    os.waitTask(my_id);
    max_no = 2650;

    for(i = 3 + (95 - 3 - 3) / 2 * thID; i < 3 + (95 - 3 - 3) / 2 * (thID + 1) + (thID + 1 == 2 && (95 - 3 - 3) % 2 != 0 ? (95 - 3 - 3) % 2 : 0); i++ )
	for(j = 3; j < 76 - 3; j++ )
	{   
	    n = 100;
	    p = image_buffer + (i - 3) * 76 + j - 1;
	    cp = bp + 258 + image_buffer[i * 76 + j];

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 3;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 5;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 6;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 2;
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 6;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 5;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 3;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);

	    if (n <= max_no)
		r[i * 76 + j] = max_no - n;
	}
    os.kill();
}

#line 1827 "susan_edge_detector.cc"
SusanEdgesThread_PartB::SusanEdgesThread_PartB(unsigned int _idcnt, unsigned char (&image_buffer)[7220], int (&r)[7220], unsigned char (&mid)[7220], unsigned char (&bp)[516], int (&thID), OSAPI (&os))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), r(r), mid(mid), bp(bp), thID(thID), os(os)
{   
}

SusanEdgesThread_PartB::~SusanEdgesThread_PartB(void)
{   
}

#line 97 "susan_edges.sc"
int SusanEdgesThread_PartB::init(void) {
    my_id = os.create();
    return my_id;
}

void SusanEdgesThread_PartB::main(void) {

    int max_no;
    float z;
    int a; int b; int do_symmetry; int i; int j; int m; int n; int w; int x; int y;
    unsigned char c; unsigned char *cp; unsigned char *p;

    os.waitTask(my_id);
    max_no = 2650;



    for(i = 4 + (95 - 4 - 4) / 2 * thID; i < 4 + (95 - 4 - 4) / 2 * (thID + 1) + (thID + 1 == 2 && (95 - 4 - 4) % 2 != 0 ? (95 - 4 - 4) % 2 : 0); i++ )
	for(j = 4; j < 76 - 4; j++ )
	{   
	    if (r[i * 76 + j] > 0)
	    {   
		m = r[i * 76 + j];
		n = max_no - m;
		cp = bp + 258 + image_buffer[i * 76 + j];

		if (n > 600)
		{   
		    p = image_buffer + (i - 3) * 76 + j - 1;
		    x = 0; y = 0;

		    c =  *(cp -  *p++ ); x -= c; y -= 3 * c;
		    c =  *(cp -  *p++ ); y -= 3 * c;
		    c =  *(cp -  *p); x += c; y -= 3 * c;
		    p += 76 - 3;

		    c =  *(cp -  *p++ ); x -= 2 * c; y -= 2 * c;
		    c =  *(cp -  *p++ ); x -= c; y -= 2 * c;
		    c =  *(cp -  *p++ ); y -= 2 * c;
		    c =  *(cp -  *p++ ); x += c; y -= 2 * c;
		    c =  *(cp -  *p); x += 2 * c; y -= 2 * c;
		    p += 76 - 5;

		    c =  *(cp -  *p++ ); x -= 3 * c; y -= c;
		    c =  *(cp -  *p++ ); x -= 2 * c; y -= c;
		    c =  *(cp -  *p++ ); x -= c; y -= c;
		    c =  *(cp -  *p++ ); y -= c;
		    c =  *(cp -  *p++ ); x += c; y -= c;
		    c =  *(cp -  *p++ ); x += 2 * c; y -= c;
		    c =  *(cp -  *p); x += 3 * c; y -= c;
		    p += 76 - 6;

		    c =  *(cp -  *p++ ); x -= 3 * c;
		    c =  *(cp -  *p++ ); x -= 2 * c;
		    c =  *(cp -  *p); x -= c;
		    p += 2;
		    c =  *(cp -  *p++ ); x += c;
		    c =  *(cp -  *p++ ); x += 2 * c;
		    c =  *(cp -  *p); x += 3 * c;
		    p += 76 - 6;

		    c =  *(cp -  *p++ ); x -= 3 * c; y += c;
		    c =  *(cp -  *p++ ); x -= 2 * c; y += c;
		    c =  *(cp -  *p++ ); x -= c; y += c;
		    c =  *(cp -  *p++ ); y += c;
		    c =  *(cp -  *p++ ); x += c; y += c;
		    c =  *(cp -  *p++ ); x += 2 * c; y += c;
		    c =  *(cp -  *p); x += 3 * c; y += c;
		    p += 76 - 5;

		    c =  *(cp -  *p++ ); x -= 2 * c; y += 2 * c;
		    c =  *(cp -  *p++ ); x -= c; y += 2 * c;
		    c =  *(cp -  *p++ ); y += 2 * c;
		    c =  *(cp -  *p++ ); x += c; y += 2 * c;
		    c =  *(cp -  *p); x += 2 * c; y += 2 * c;
		    p += 76 - 3;

		    c =  *(cp -  *p++ ); x -= c; y += 3 * c;
		    c =  *(cp -  *p++ ); y += 3 * c;
		    c =  *(cp -  *p); x += c; y += 3 * c;

		    z = sqrt((float)((x * x) + (y * y)));
		    if (z > (9.000000000000000e-01 * (float)n))
		    {   
			do_symmetry = 0;
			if (x == 0)
			    z = 1.000000000000000e+06;
			else 
			    z = ((float)y) / ((float)x);
			if (z < 0) { z =  -z; w =  -1;
			}
			else 

#line 187 "susan_edges.sc"
			    w = 1;
			if (z < 5.000000000000000e-01) { a = 0; b = 1;
			}
			else 

#line 189 "susan_edges.sc"
			{    if (z > 2.000000000000000e+00) { a = 1; b = 0;
			    }
			    else 

#line 190 "susan_edges.sc"
			    {    if (w > 0) { a = 1; b = 1;
				}
				else 

#line 191 "susan_edges.sc"
				{    a =  -1; b = 1;
				}
			    }
			}

#line 192 "susan_edges.sc"
			if ((m > r[(i + a) * 76 + j + b]) && (m >= r[(i - a) * 76 + j - b]) && 
			    (m > r[(i + (2 * a)) * 76 + j + (2 * b)]) && (m >= r[(i - (2 * a)) * 76 + j - (2 * b)]))
			    mid[i * 76 + j] = 1;
		    }
		    else 
			do_symmetry = 1;
		}
		else 
		    do_symmetry = 1;

		if (do_symmetry == 1)
		{   
		    p = image_buffer + (i - 3) * 76 + j - 1;
		    x = 0; y = 0; w = 0;

#line 211 "susan_edges.sc"
		    c =  *(cp -  *p++ ); x += c; y += 9 * c; w += 3 * c;
		    c =  *(cp -  *p++ ); y += 9 * c;
		    c =  *(cp -  *p); x += c; y += 9 * c; w -= 3 * c;
		    p += 76 - 3;

		    c =  *(cp -  *p++ ); x += 4 * c; y += 4 * c; w += 4 * c;
		    c =  *(cp -  *p++ ); x += c; y += 4 * c; w += 2 * c;
		    c =  *(cp -  *p++ ); y += 4 * c;
		    c =  *(cp -  *p++ ); x += c; y += 4 * c; w -= 2 * c;
		    c =  *(cp -  *p); x += 4 * c; y += 4 * c; w -= 4 * c;
		    p += 76 - 5;

		    c =  *(cp -  *p++ ); x += 9 * c; y += c; w += 3 * c;
		    c =  *(cp -  *p++ ); x += 4 * c; y += c; w += 2 * c;
		    c =  *(cp -  *p++ ); x += c; y += c; w += c;
		    c =  *(cp -  *p++ ); y += c;
		    c =  *(cp -  *p++ ); x += c; y += c; w -= c;
		    c =  *(cp -  *p++ ); x += 4 * c; y += c; w -= 2 * c;
		    c =  *(cp -  *p); x += 9 * c; y += c; w -= 3 * c;
		    p += 76 - 6;

		    c =  *(cp -  *p++ ); x += 9 * c;
		    c =  *(cp -  *p++ ); x += 4 * c;
		    c =  *(cp -  *p); x += c;
		    p += 2;
		    c =  *(cp -  *p++ ); x += c;
		    c =  *(cp -  *p++ ); x += 4 * c;
		    c =  *(cp -  *p); x += 9 * c;
		    p += 76 - 6;

		    c =  *(cp -  *p++ ); x += 9 * c; y += c; w -= 3 * c;
		    c =  *(cp -  *p++ ); x += 4 * c; y += c; w -= 2 * c;
		    c =  *(cp -  *p++ ); x += c; y += c; w -= c;
		    c =  *(cp -  *p++ ); y += c;
		    c =  *(cp -  *p++ ); x += c; y += c; w += c;
		    c =  *(cp -  *p++ ); x += 4 * c; y += c; w += 2 * c;
		    c =  *(cp -  *p); x += 9 * c; y += c; w += 3 * c;
		    p += 76 - 5;

		    c =  *(cp -  *p++ ); x += 4 * c; y += 4 * c; w -= 4 * c;
		    c =  *(cp -  *p++ ); x += c; y += 4 * c; w -= 2 * c;
		    c =  *(cp -  *p++ ); y += 4 * c;
		    c =  *(cp -  *p++ ); x += c; y += 4 * c; w += 2 * c;
		    c =  *(cp -  *p); x += 4 * c; y += 4 * c; w += 4 * c;
		    p += 76 - 3;

		    c =  *(cp -  *p++ ); x += c; y += 9 * c; w -= 3 * c;
		    c =  *(cp -  *p++ ); y += 9 * c;
		    c =  *(cp -  *p); x += c; y += 9 * c; w += 3 * c;

		    if (y == 0)
			z = 1.000000000000000e+06;
		    else 
			z = ((float)x) / ((float)y);
		    if (z < 5.000000000000000e-01) { a = 0; b = 1;
		    }
		    else 

#line 266 "susan_edges.sc"
		    {    if (z > 2.000000000000000e+00) { a = 1; b = 0;
			}
			else 

#line 267 "susan_edges.sc"
			{    if (w > 0) { a =  -1; b = 1;
			    }
			    else 

#line 268 "susan_edges.sc"
			    {    a = 1; b = 1;
			    }
			}
		    }

#line 269 "susan_edges.sc"
		    if ((m > r[(i + a) * 76 + j + b]) && (m >= r[(i - a) * 76 + j - b]) && 
			(m > r[(i + (2 * a)) * 76 + j + (2 * b)]) && (m >= r[(i - (2 * a)) * 76 + j - (2 * b)]))
			mid[i * 76 + j] = 2;
		}
	    }
	}
    os.kill();
}

#line 2054 "susan_edge_detector.cc"
SusanEdges_ReadInput::SusanEdges_ReadInput(unsigned int _idcnt, i_receiver (&in_image), unsigned char (&in_image_buffer)[7220], int (&r)[7220], unsigned char (&mid)[7220])
    : _specc::behavior(_idcnt), in_image(in_image), in_image_buffer(in_image_buffer), r(r), mid(mid)
{   
}

SusanEdges_ReadInput::~SusanEdges_ReadInput(void)
{   
}

#line 281 "susan_edges.sc"
void SusanEdges_ReadInput::main(void) {



    in_image.receive( &in_image_buffer, sizeof (in_image_buffer));

    memset(mid, 100, 76 * 95);
    memset(r, 0, 76 * 95 * sizeof(int));
}

#line 2075 "susan_edge_detector.cc"
SusanEdges_WriteOutput::SusanEdges_WriteOutput(unsigned int _idcnt, i_int7220_sender_os (&out_r), i_uchar7220_sender_os (&out_mid), i_uchar7220_sender_os (&out_image), int (&r)[7220], unsigned char (&mid)[7220], unsigned char (&out_image_buffer)[7220])
    : _specc::behavior(_idcnt), out_r(out_r), out_mid(out_mid), out_image(out_image), r(r), mid(mid), out_image_buffer(out_image_buffer)
{   
}

SusanEdges_WriteOutput::~SusanEdges_WriteOutput(void)
{   
}

#line 297 "susan_edges.sc"
void SusanEdges_WriteOutput::main(void) {
    out_r.send(r);
    out_mid.send(mid);
    out_image.send(out_image_buffer);
}

#line 2092 "susan_edge_detector.cc"
SusanEdges_PartA::SusanEdges_PartA(unsigned int _idcnt, unsigned char (&image_buffer)[7220], int (&r)[7220], unsigned char (&bp)[516], OSAPI (&os))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), r(r), bp(bp), os(os),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    susan_edges_a_thread_0(_IDcnt, image_buffer, r, bp, _scc_const_port_0, os),
    susan_edges_a_thread_1(_IDcnt, image_buffer, r, bp, _scc_const_port_1, os)
{   
}

SusanEdges_PartA::~SusanEdges_PartA(void)
{   
}

#line 311 "susan_edges.sc"
void SusanEdges_PartA::main(void) {
    my_id = os.getMyID();
    my_id0 = susan_edges_a_thread_0.init();
    my_id1 = susan_edges_a_thread_1.init();

    os.par_start(my_id);
    { _specc::fork _scc_fork_0(&susan_edges_a_thread_0), _scc_fork_1(&susan_edges_a_thread_1); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, ((_specc::fork*)0));
    }
    os.par_end(my_id);
    os.timewait(19000000);
}

#line 2121 "susan_edge_detector.cc"
SusanEdges_PartB::SusanEdges_PartB(unsigned int _idcnt, unsigned char (&image_buffer)[7220], int (&r)[7220], unsigned char (&mid)[7220], unsigned char (&bp)[516], OSAPI (&os))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), r(r), mid(mid), bp(bp), os(os),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    susan_edges_b_thread_0(_IDcnt, image_buffer, r, mid, bp, _scc_const_port_0, os),
    susan_edges_b_thread_1(_IDcnt, image_buffer, r, mid, bp, _scc_const_port_1, os)
{   
}

SusanEdges_PartB::~SusanEdges_PartB(void)
{   
}

#line 334 "susan_edges.sc"
void SusanEdges_PartB::main(void) {
    my_id = os.getMyID();
    my_id0 = susan_edges_b_thread_0.init();
    my_id1 = susan_edges_b_thread_1.init();

    os.par_start(my_id);
    { _specc::fork _scc_fork_0(&susan_edges_b_thread_0), _scc_fork_1(&susan_edges_b_thread_1); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, ((_specc::fork*)0));
    }
    os.par_end(my_id);
    os.timewait(20000000);
}

#line 2150 "susan_edge_detector.cc"
SusanEdges::SusanEdges(unsigned int _idcnt, i_receiver (&in_image), i_int7220_sender_os (&out_r), i_uchar7220_sender_os (&out_mid), unsigned char (&bp)[516], i_uchar7220_sender_os (&out_image), OSAPI (&os))
    : _specc::behavior(_idcnt), in_image(in_image), out_r(out_r), out_mid(out_mid), bp(bp), out_image(out_image), os(os),
    susan_edges_a(_IDcnt, image_buffer, r, bp, os),
    susan_edges_b(_IDcnt, image_buffer, r, mid, bp, os),
    susan_edges_read_input(_IDcnt, in_image, image_buffer, r, mid),
    susan_edges_write_output(_IDcnt, out_r, out_mid, out_image, r, mid, image_buffer)
{   
}

SusanEdges::~SusanEdges(void)
{   
}

#line 363 "susan_edges.sc"
void SusanEdges::main(void) {

    { enum { _scc_state_0, _scc_state_susan_edges_read_input, _scc_state_susan_edges_a, _scc_state_susan_edges_b, _scc_state_susan_edges_write_output } _scc_next_state = _scc_state_susan_edges_read_input; do switch(_scc_next_state) {
	    case _scc_state_susan_edges_read_input: { susan_edges_read_input.main(); { _scc_next_state = _scc_state_susan_edges_a; break; } }
	    case _scc_state_susan_edges_a: { susan_edges_a.main(); { _scc_next_state = _scc_state_susan_edges_b; break; } }
	    case _scc_state_susan_edges_b: { susan_edges_b.main(); { _scc_next_state = _scc_state_susan_edges_write_output; break; } }
	    case _scc_state_susan_edges_write_output: { susan_edges_write_output.main(); { _scc_next_state = _scc_state_0; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }
}

#line 2175 "susan_edge_detector.cc"
SusanThinThread::SusanThinThread(unsigned int _idcnt, int (&r)[7220], unsigned char (&mid)[7220], int (&thID), OSAPI (&os))
    : _specc::behavior(_idcnt), r(r), mid(mid), thID(thID), os(os)
{   
}

SusanThinThread::~SusanThinThread(void)
{   
}

#line 12 "susan_thin.sc"
int SusanThinThread::init(void) {
    my_id = os.create();
    return my_id;
}

void SusanThinThread::main(void) {
    int centre; int l[9];
    int b01; int b10; int b12; int b21;
    int p1; int p2; int p3; int p4;
    int b00; int b02; int b20; int b22;
    int a; int b; int i; int j; int m; int n; int x; int y;
    unsigned char *mp;

    os.waitTask(my_id);

    for(i = 4 + (95 - 4 - 4) / 2 * thID; i < 4 + (95 - 4 - 4) / 2 * (thID + 1) + (thID + 1 == 2 && (95 - 4 - 4) % 2 != 0 ? (95 - 4 - 4) % 2 : 0); i++ )

	for(j = 4; j < 76 - 4; j++ )
	    if (mid[i * 76 + j] < 8)
	    {   
		centre = r[i * 76 + j];


		mp = mid + (i - 1) * 76 + j - 1;

		n = ( *mp < 8) + 
		( *(mp + 1) < 8) + 
		( *(mp + 2) < 8) + 
		( *(mp + 76) < 8) + 
		( *(mp + 76 + 2) < 8) + 
		( *(mp + 76 + 76) < 8) + 
		( *(mp + 76 + 76 + 1) < 8) + 
		( *(mp + 76 + 76 + 2) < 8);



		if (n == 0)
		    mid[i * 76 + j] = 100;




		if ((n == 1) && (mid[i * 76 + j] < 6))
		{   

#line 62 "susan_thin.sc"
		    l[0] = r[(i - 1) * 76 + j - 1]; l[1] = r[(i - 1) * 76 + j]; l[2] = r[(i - 1) * 76 + j + 1];
		    l[3] = r[(i) * 76 + j - 1]; l[4] = 0; l[5] = r[(i) * 76 + j + 1];
		    l[6] = r[(i + 1) * 76 + j - 1]; l[7] = r[(i + 1) * 76 + j]; l[8] = r[(i + 1) * 76 + j + 1];

		    if (mid[(i - 1) * 76 + j - 1] < 8) { l[0] = 0; l[1] = 0; l[3] = 0; l[2] *= 2;
			l[6] *= 2; l[5] *= 3; l[7] *= 3; l[8] *= 4;
		    }
		    else 

#line 68 "susan_thin.sc"
		    {    if (mid[(i - 1) * 76 + j] < 8) { l[1] = 0; l[0] = 0; l[2] = 0; l[3] *= 2;
			    l[5] *= 2; l[6] *= 3; l[8] *= 3; l[7] *= 4;
			}
			else 

#line 70 "susan_thin.sc"
			{    if (mid[(i - 1) * 76 + j + 1] < 8) { l[2] = 0; l[1] = 0; l[5] = 0; l[0] *= 2;
				l[8] *= 2; l[3] *= 3; l[7] *= 3; l[6] *= 4;
			    }
			    else 

#line 72 "susan_thin.sc"
			    {    if (mid[(i) * 76 + j - 1] < 8) { l[3] = 0; l[0] = 0; l[6] = 0; l[1] *= 2;
				    l[7] *= 2; l[2] *= 3; l[8] *= 3; l[5] *= 4;
				}
				else 

#line 74 "susan_thin.sc"
				{    if (mid[(i) * 76 + j + 1] < 8) { l[5] = 0; l[2] = 0; l[8] = 0; l[1] *= 2;
					l[7] *= 2; l[0] *= 3; l[6] *= 3; l[3] *= 4;
				    }
				    else 

#line 76 "susan_thin.sc"
				    {    if (mid[(i + 1) * 76 + j - 1] < 8) { l[6] = 0; l[3] = 0; l[7] = 0; l[0] *= 2;
					    l[8] *= 2; l[1] *= 3; l[5] *= 3; l[2] *= 4;
					}
					else 

#line 78 "susan_thin.sc"
					{    if (mid[(i + 1) * 76 + j] < 8) { l[7] = 0; l[6] = 0; l[8] = 0; l[3] *= 2;
						l[5] *= 2; l[0] *= 3; l[2] *= 3; l[1] *= 4;
					    }
					    else 

#line 80 "susan_thin.sc"
					    {    if (mid[(i + 1) * 76 + j + 1] < 8) { l[8] = 0; l[5] = 0; l[7] = 0; l[6] *= 2;
						    l[2] *= 2; l[1] *= 3; l[3] *= 3; l[0] *= 4;
						}
					    }
					}
				    }
				}
			    }
			}
		    }

#line 83 "susan_thin.sc"
		    m = 0;
		    for(y = 0; y < 3; y++ )
			for(x = 0; x < 3; x++ )
			    if (l[y + y + y + x] > m) { m = l[y + y + y + x]; a = y; b = x;
			    }
		    if (m > 0)
		    {   
			if (mid[i * 76 + j] < 4)
			    mid[(i + a - 1) * 76 + j + b - 1] = 4;
			else 
			    mid[(i + a - 1) * 76 + j + b - 1] = mid[i * 76 + j] + 1;
			if ((a + a + b) < 3)
			{   
			    i += a - 1;
			    j += b - 2;
			    if (i < 4) i = 4;
			    if (j < 4) j = 4;
			}
		    }
		}

		if (n == 2)
		{   

		    b00 = mid[(i - 1) * 76 + j - 1] < 8;
		    b02 = mid[(i - 1) * 76 + j + 1] < 8;
		    b20 = mid[(i + 1) * 76 + j - 1] < 8;
		    b22 = mid[(i + 1) * 76 + j + 1] < 8;
		    if (((b00 + b02 + b20 + b22) == 2) && ((b00 | b22) & (b02 | b20)))
		    {   



			if (b00)
			{   
			    if (b02) { x = 0; y =  -1;
			    }
			    else 

#line 119 "susan_thin.sc"
			    {    x =  -1; y = 0;
			    }
			}
			else  {
			    if (b02) { x = 1; y = 0;
			    }
			    else 

#line 124 "susan_thin.sc"
			    {    x = 0; y = 1;
			    }
			} if (((float)r[(i + y) * 76 + j + x] / (float)centre) > 7.000000000000000e-01)
			{   
			    if (((x == 0) && (mid[(i + (2 * y)) * 76 + j] > 7) && (mid[(i + (2 * y)) * 76 + j - 1] > 7) && (mid[(i + (2 * y)) * 76 + j + 1] > 7)) || 
				((y == 0) && (mid[(i) * 76 + j + (2 * x)] > 7) && (mid[(i + 1) * 76 + j + (2 * x)] > 7) && (mid[(i - 1) * 76 + j + (2 * x)] > 7)))
			    {   
				mid[(i) * 76 + j] = 100;
				mid[(i + y) * 76 + j + x] = 3;
			    }
			}
		    }
		    else 
		    {   
			b01 = mid[(i - 1) * 76 + j] < 8;
			b12 = mid[(i) * 76 + j + 1] < 8;
			b21 = mid[(i + 1) * 76 + j] < 8;
			b10 = mid[(i) * 76 + j - 1] < 8;

#line 166 "susan_thin.sc"
			if (((b01 + b12 + b21 + b10) == 2) && ((b10 | b12) & (b01 | b21)) && 
			    ((b01 & ((mid[(i - 2) * 76 + j - 1] < 8) | (mid[(i - 2) * 76 + j + 1] < 8))) | (b10 & ((mid[(i - 1) * 76 + j - 2] < 8) | (mid[(i + 1) * 76 + j - 2] < 8))) | 
				(b12 & ((mid[(i - 1) * 76 + j + 2] < 8) | (mid[(i + 1) * 76 + j + 2] < 8))) | (b21 & ((mid[(i + 2) * 76 + j - 1] < 8) | (mid[(i + 2) * 76 + j + 1] < 8)))))
			{   



			    mid[(i) * 76 + j] = 100;
			    i-- ;
			    j -= 2;
			    if (i < 4) i = 4;
			    if (j < 4) j = 4;
			}
		    }
		}

		if (n > 2)
		{   
		    b01 = mid[(i - 1) * 76 + j] < 8;
		    b12 = mid[(i) * 76 + j + 1] < 8;
		    b21 = mid[(i + 1) * 76 + j] < 8;
		    b10 = mid[(i) * 76 + j - 1] < 8;
		    if ((b01 + b12 + b21 + b10) > 1)
		    {   
			b00 = mid[(i - 1) * 76 + j - 1] < 8;
			b02 = mid[(i - 1) * 76 + j + 1] < 8;
			b20 = mid[(i + 1) * 76 + j - 1] < 8;
			b22 = mid[(i + 1) * 76 + j + 1] < 8;
			p1 = b00 | b01;
			p2 = b02 | b12;
			p3 = b22 | b21;
			p4 = b20 | b10;

			if (((p1 + p2 + p3 + p4) - ((b01 & p2) + (b12 & p3) + (b21 & p4) + (b10 & p1))) < 2)
			{   
			    mid[(i) * 76 + j] = 100;
			    i-- ;
			    j -= 2;
			    if (i < 4) i = 4;
			    if (j < 4) j = 4;
			}
		    }
		}
	    }
    os.kill();
}

#line 2406 "susan_edge_detector.cc"
SusanThin_ReadInput::SusanThin_ReadInput(unsigned int _idcnt, i_int7220_receiver_os (&in_r), i_uchar7220_receiver_os (&in_mid), int (&r)[7220], unsigned char (&mid)[7220])
    : _specc::behavior(_idcnt), in_r(in_r), in_mid(in_mid), r(r), mid(mid)
{   
}

SusanThin_ReadInput::~SusanThin_ReadInput(void)
{   
}

#line 218 "susan_thin.sc"
void SusanThin_ReadInput::main(void) {

    in_r.receive( &r);

    in_mid.receive( &mid);
}

#line 2424 "susan_edge_detector.cc"
SusanThin_WriteOutput::SusanThin_WriteOutput(unsigned int _idcnt, i_uchar7220_sender_os (&out_mid), unsigned char (&mid)[7220])
    : _specc::behavior(_idcnt), out_mid(out_mid), mid(mid)
{   
}

SusanThin_WriteOutput::~SusanThin_WriteOutput(void)
{   
}

#line 229 "susan_thin.sc"
void SusanThin_WriteOutput::main(void) {

    out_mid.send(mid);
}

#line 2440 "susan_edge_detector.cc"
SusanThin::SusanThin(unsigned int _idcnt, int (&r)[7220], unsigned char (&mid)[7220], OSAPI (&os))
    : _specc::behavior(_idcnt), r(r), mid(mid), os(os),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    susan_thin_thread_0(_IDcnt, r, mid, _scc_const_port_0, os),
    susan_thin_thread_1(_IDcnt, r, mid, _scc_const_port_1, os)
{   
}

SusanThin::~SusanThin(void)
{   
}

#line 244 "susan_thin.sc"
void SusanThin::main(void) {
    my_id = os.getMyID();
    my_id0 = susan_thin_thread_0.init();
    my_id1 = susan_thin_thread_1.init();

    os.par_start(my_id);
    { _specc::fork _scc_fork_0(&susan_thin_thread_0), _scc_fork_1(&susan_thin_thread_1); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, ((_specc::fork*)0));
    }
    os.par_end(my_id);

    os.timewait(6400000);
}

#line 2470 "susan_edge_detector.cc"
Thin::Thin(unsigned int _idcnt, i_int7220_receiver_os (&in_r), i_uchar7220_receiver_os (&in_mid), i_uchar7220_sender_os (&out_mid), OSAPI (&os))
    : _specc::behavior(_idcnt), in_r(in_r), in_mid(in_mid), out_mid(out_mid), os(os),
    susan_thin(_IDcnt, r, mid, os),
    susan_thin_read_input(_IDcnt, in_r, in_mid, r, mid),
    susan_thin_write_output(_IDcnt, out_mid, mid)
{   
}

Thin::~Thin(void)
{   
}

#line 273 "susan_thin.sc"
int Thin::init(void) {
    my_id = os.create();
    return my_id;
}

void Thin::main(void) {

    os.waitTask(my_id);
    { enum { _scc_state_0, _scc_state_susan_thin_read_input, _scc_state_susan_thin, _scc_state_susan_thin_write_output } _scc_next_state = _scc_state_susan_thin_read_input; do switch(_scc_next_state) {
	    case _scc_state_susan_thin_read_input: { susan_thin_read_input.main(); { _scc_next_state = _scc_state_susan_thin; break; } }
	    case _scc_state_susan_thin: { susan_thin.main(); { _scc_next_state = _scc_state_susan_thin_write_output; break; } }
	    case _scc_state_susan_thin_write_output: { susan_thin_write_output.main(); { _scc_next_state = _scc_state_susan_thin_read_input; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }
    os.kill();
}

#line 2500 "susan_edge_detector.cc"
WriteImage::WriteImage(unsigned int _idcnt, i_receiver (&in_image), i_sender (&out_image))
    : _specc::behavior(_idcnt), in_image(in_image), out_image(out_image)
{   
}

WriteImage::~WriteImage(void)
{   
}

#line 10 "write_image.sc"
void WriteImage::main(void) {
    unsigned char image_buffer[7220];

    while(true) {


	in_image.receive( &image_buffer, sizeof (image_buffer));
	out_image.send(image_buffer, sizeof (image_buffer));
    }
}

#line 2522 "susan_edge_detector.cc"
void _scc_bit4_err_handle(
    const _bit4& bit4vec)
{   
    char temp_bits[1024], *p;
    p=bit2str(2,&temp_bits[1023], bit4vec);
    _specc::abort(
	"ERROR:\t Casting a bit4 vector failed \n"
	"Bit4 vector contains X/Z values %s\n"
	"Simulation aborted.\n", p);
	
}

//////////////////////////////////////////////////////////////////////
// End of file susan_edge_detector.cc
//////////////////////////////////////////////////////////////////////
